name: macOS Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: macOS Build
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: pod install
        working-directory: ./macos
        run: pod install
